import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { Header } from '@/components/shared/Header/Header'
import { Footer } from '@/components/shared/Footer/Footer'
import { Providers } from '@/lib/Components/providers'
import { FooterMobile } from '@/components/shared/Footer/Footer-mobile'

const nunito = Nunito({
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: '0606',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="dark" lang="en">
      <body className={cn('min-h-screen flex flex-col scroll__hidden', nunito.className)}>
        <Providers>
          <Header />
          <main className="flex-1 flex flex-col">{children}</main>
          <Footer />
          <FooterMobile />
        </Providers>
      </body>
    </html>
  )
}
